name: Build and Deploy to Render

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE_NAME: cadastro-usuarios
  DOCKER_REGISTRY: docker.io
  RENDER_API_URL: https://api.render.com/v1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Deploy to Render
        run: |
          SERVICE_ID=$(curl -s -X GET \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
            "${{ env.RENDER_API_URL }}/services?name=${{ secrets.RENDER_SERVICE_NAME }}" \
            | jq -r '.[0].id')

          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"clearCache": "clear"}' \
            "${{ env.RENDER_API_URL }}/services/$SERVICE_ID/deploys"